/*
 * This Java source file was generated by the Gradle 'init' task.
 */
//package webtest;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.annotation.WebServlet;
import java.io.PrintWriter;


@WebServlet(urlPatterns={"/exemplo_01"})
public class App extends HttpServlet{	//App é o nome do arquivo dentro do /main/java
	@Override
	public void doGet(HttpServletRequest req, HttpServletResponse res){
		try{
			PrintWriter pw = res.getWriter();
			pw.write("Build com Gradle Funcionando!!");
			pw.close();
		} catch (Exception e){
			System.out.println("Erro em IO ou servlet");
		}
	}
}